In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [47]:
df = pd.read_csv('./file_new/auto-mpg_v2.csv')
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0  3504.0          12.0   
1    15.0          8         350.0       165.0  3693.0          11.5   
2    18.0          8         318.0       150.0  3436.0          11.0   
3    16.0          8         304.0       150.0  3433.0          12.0   
4    17.0          8         302.0       140.0  3449.0          10.5   
..    ...        ...           ...         ...     ...           ...   
387  27.0          4         140.0        86.0  2790.0          15.6   
388  44.0          4          97.0        52.0  2130.0          24.6   
389  32.0          4         135.0        84.0  2295.0          11.6   
390  28.0          4         120.0        79.0  2625.0          18.6   
391  31.0          4         119.0        82.0  2720.0          19.4   

     model year  origin                       name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
387          82       1            ford mustang gl  
388          82       2                  vw pickup  
389          82       1              dodge rampage  
390          82       1                ford ranger  
391          82       1                 chevy s-10  

[392 rows x 9 columns]

In [48]:
ndf = df[['mpg', 'cylinders' ,'horsepower', 'weight']]
ndf

mpg  cylinders  horsepower  weight
0    18.0          8       130.0  3504.0
1    15.0          8       165.0  3693.0
2    18.0          8       150.0  3436.0
3    16.0          8       150.0  3433.0
4    17.0          8       140.0  3449.0
..    ...        ...         ...     ...
387  27.0          4        86.0  2790.0
388  44.0          4        52.0  2130.0
389  32.0          4        84.0  2295.0
390  28.0          4        79.0  2625.0
391  31.0          4        82.0  2720.0

[392 rows x 4 columns]

## 1. 학습
### 1. 1 train_test_split
#### - test_size: 검증 데이터 비율 (나머지 훈련 데이터 비율)
#### - random_state: 랜덤하게 뽑아내기 위한 시드값
#### - train: 훈련 데이터 
####  - test: 검증 데이터

In [49]:
x = ndf[['weight']]
y = ndf[['mpg']]

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
x_train, x_test, y_train, y_test, = train_test_split(x,
                                                     y,
                                                     test_size = 0.3,
                                                     random_state = 10)

In [52]:
x_train

weight
37   4209.0
170  2223.0
275  3410.0
194  2164.0
352  2615.0
..      ...
369  1980.0
320  2110.0
15   2833.0
125  2901.0
265  2560.0

[274 rows x 1 columns]

### 1.2 학습모델 만들기

In [53]:
from sklearn.linear_model import LinearRegression

In [54]:
lr = LinearRegression()

In [55]:
lr.fit(x_train, y_train)

LinearRegression()

In [56]:
lr.score(x_train, y_train)

0.6916618001977128

#### - a 값

In [57]:
lr.coef_

array([[-0.00775343]])

#### - b 값

In [58]:
lr.intercept_

array([46.71036626])

In [59]:
y_hat = lr.predict(x)
y_hat

array([[19.54234168],
       [18.0769431 ],
       [20.06957503],
       [20.09283533],
       [19.96878042],
       [13.05271937],
       [12.95192476],
       [13.27756889],
       [12.40143111],
       [16.85965432],
       [19.08488921],
       [18.72823136],
       [17.54970974],
       [22.78327612],
       [28.31922633],
       [24.74489433],
       [25.2023468 ],
       [26.65223852],
       [30.1955568 ],
       [32.48281914],
       [25.99319683],
       [27.8695273 ],
       [28.29596604],
       [29.3891999 ],
       [26.17927919],
       [10.92827909],
       [12.78134926],
       [12.73482867],
       [10.02112759],
       [30.1955568 ],
       [29.15659695],
       [29.43572049],
       [26.28782724],
       [20.04631474],
       [20.89919222],
       [21.10853488],
       [21.21708292],
       [14.07617235],
       [12.09904728],
       [14.50261109],
       [14.95231013],
       [ 8.29211233],
       [ 9.91257955],
       [ 6.85772747],
       [23.74470165],
       [28

In [61]:
plt.figure(figsize = (10, 5))
ax1 = sns.kdeplot(y, label = "y")
ax2 = sns.kdeplot(y_hat, label = "y_hat", ax = ax1)

plt.legend()
plt.show()

ValueError: If using all scalar values, you must pass an index

<Figure size 720x360 with 0 Axes>